---
title: Intervenciones hipotéticas para disminuir la presión arterial, y el riesgo
  de accidente cerebrovascular y demencia
authors: 
- L. Paloma Rojas-Saunero
- Saima Hilal
- Eleanor Murray
- Roger Logan
- M. Arfan Ikram
- Sonja A. Swanson
author_notes:
- Equal contribution
- Equal contribution
date: '2020-11-27'
slug: eje2020
categories: []
tags: [hipertensión arterial, demencia, ACV, ensayo ideal, g-formula]
subtitle: 'Traducción de: Hypothetical blood-pressure-lowering interventions and risk of stroke and dementia.'
summary: ''
lastmod: '2021-02-13T20:52:49+01:00'
featured: yes
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
links:
- icon: file-alt
  icon_pack: fas
  name: v. traducida
  url: "https://static-content.springer.com/esm/art%3A10.1007%2Fs10654-020-00694-5/MediaObjects/10654_2020_694_MOESM2_ESM.pdf"
- icon: file-pdf
  icon_pack: fas
  name: v. original
  url: "https://link.springer.com/content/pdf/10.1007/s10654-020-00694-5.pdf"
- icon: scroll
  icon_pack: fas
  name: código fuente
  url: "https://github.com/palolili23/ht_trial_gformula"
publication: European Journal of Epidemiology
doi: "https://doi.org/10.1007/s10654-020-00694-5"
---

**Objetivo:** Estimar los efectos de intervenciones hipotéticas en la presión arterial sistólica (PAS) y en el hábito de fumar en el riesgo de accidente cerebrovascular (ACV) y el riesgo de demencia usando datos de 15 años de
seguimiento dentro del Estudio de Rotterdam.

**Métodos:** Usamos datos de 4930 personas, con edad de 55-80 años, sin antecedente de ACV, deterioro cognitivo, demencia y seguidos durante 15 años dentro del Estudio de Rotterdam, una cohorte poblacional. Definimos las siguientes intervenciones sostenidas en la PAS (1) mantener la PAS debajo de 120 mmHg, (2) mantener la PAS debajo de 140 mmHg, (3) reducir la PAS en un 10% si es mayor a 140 mmHg, (4) reducir la PAS en 20% si es mayor a 140 mmHg, e intervenciones que combinan la intervención de dejar de fumar con cada una de las estrategias propuestas para disminuir la PAS. Consideramos como evento el caso incidente de ACV y el diagnóstico incidente de demencia. Aplicamos la g-formula paramétrica para ajustar por variables confundidoras fijas y que varían en el tiempo.

**Resultados:** El riesgo observado de ACV a 15 años fue del 10.7%. Comparando con la intervención no especificada (“el curso natural”), todas las intervenciones que reducen la PAS estuvieron asociadas con una reducción del riesgo de ACV de alrededor del 10% (ej. Reducir la PAS en 20% si es mayor a 140mmHg, riesgo relativo: 0.89; IC95%: 0.76, 1). Intervenciones conjuntas en la PAS y dejar de fumar disminuyeron más el riesgo de ACV (ej. riesgo relativo: 0.83; IC95%: 0.71, 0.94). Ninguna de las intervenciones especificadas estuvieron
asociadas con un cambio substancial en el riesgo de demencia. 

**Conclusiones:** Nuestro estudio sugiere que intervenciones conjuntas en la PAS y dejar de fumar pueden disminuir el riesgo de ACV en la edad tardía, mientras que el potencial para reducir el riesgo de demencia no fue
observado.
