---
title: Hypothetical blood-pressure-lowering interventions and risk of stroke and dementia
authors: 
- L. Paloma Rojas-Saunero
- Saima Hilal
- Eleanor Murray
- Roger Logan
- M. Arfan Ikram
- Sonja A. Swanson
author_notes:
- Equal contribution
- Equal contribution
date: '2020-11-27'
slug: eje2020
categories: []
tags: [Target trial, G-Formula, Hypertension, Stroke, Dementia]
subtitle: ''
summary: ''
lastmod: '2021-02-13T20:52:49+01:00'
featured: yes
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
links:
- icon: file-pdf
  icon_pack: fas
  name: original v.
  url: "https://link.springer.com/content/pdf/10.1007/s10654-020-00694-5.pdf"
- icon: file-alt
  icon_pack: fas
  name: translated v.
  url: "https://static-content.springer.com/esm/art%3A10.1007%2Fs10654-020-00694-5/MediaObjects/10654_2020_694_MOESM2_ESM.pdf"
- icon: scroll
  icon_pack: fas
  name: code
  url: "https://github.com/palolili23/ht_trial_gformula"
publication: European Journal of Epidemiology
doi: "https://doi.org/10.1007/s10654-020-00694-5"
---

We aimed to study the effects of hypothetical interventions on systolic blood pressure (SBP) and smoking on risk of stroke and dementia using data from 15 years of follow-up in the Rotterdam Study. We used data from 4930 individuals, aged 55–80 years, with no prior history of stroke, dementia or cognitive impairment, followed for 15 years within the Rotterdam Study, a population-based cohort. We defined the following sustained interventions on SBP: (1) maintaining SBP below 120 mmHg, (2) maintaining SBP below 140 mmHg, (3) reducing SBP by 10% if above 140 mmHg, (4) reducing SBP by 20% if above 140 mmHg, and a combined intervention of quitting smoking with each of these SBP-lowering strategies. We considered incident stroke and incident dementia diagnoses as outcomes. We applied the parametric g-formula to adjust for baseline and time-varying confounding. The observed 15-year risk for stroke was 10.7%. Compared to no specified intervention (i.e., the “natural course”), all interventions that involved reducing SBP were associated with a stroke risk reduction of about 10% (e.g., reducing SBP by 20% if above 140 mmHg risk ratio: 0.89; 95% CI 0.76, 1). Jointly intervening on SBP and smoking status further decreased the risk of stroke (e.g., risk ratio: 0.83; 95% CI 0.71, 0.94). None of the specified interventions were associated with a substantive change in dementia risk. Our study suggests that a joint intervention on SBP and smoking cessation during later life may reduce stroke risk, while the potential for reducing dementia risk were not observed."
